# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ant-routing', ['internet',])
    module.includes = '.'
    module.source = [
        'model/ant-routing.cc',
        'model/ant-routing-table.cc',
        'helper/ant-routing-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ant-routing')
    module_test.source = [
        'test/ant-routing-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'ant-routing'
    headers.source = [
        'model/ant-routing.h',
        'model/ant-routing-table.h',
        'helper/ant-routing-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()
